version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: orgpulse-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: orgpulse
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: orgpulse-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local